spring.application.name=library
server.port=8080

spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tselios1990@gmail.com
spring.mail.password=123456!a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



spring.datasource.url=jdbc:postgresql://localhost:5432/crewnow_db
spring.datasource.username=crewnow_user
spring.datasource.password=123456!a

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

#Run in command line  for Windows
#./mvnw spring-boot:run -Dspring-boot.run.profiles=office
upload.path=/home/user/IdeaProjects/job-platform/uploads/images/